import {useEffect,useState,type FormEvent,type ReactNode} from 'react';
import {Link} from 'react-router-dom';
import {LayoutDashboard,ShoppingBag,Package,Clapperboard,Store,BarChart3,Crown,Settings,Users,Flag,Image,FileText,CreditCard,Star,Plus,ArrowUpRight,Trash2} from 'lucide-react';
import {useStore} from '../lib/store';
import {api,send,money} from '../lib/api';
import {Empty,Modal} from '../components/ui';
import {categories} from '../../shared/catalog';
import {VideoUpload} from '../components/VideoUpload';
const sellerTabs=[['Overview',LayoutDashboard],['Products',ShoppingBag],['Orders',Package],['Inventory',Package],['Reels',Clapperboard],['Posts',FileText],['Brand',Store],['Analytics',BarChart3],['Premium',Crown],['Settings',Settings]] as const;
const adminTabs=[['Dashboard',LayoutDashboard],['Users',Users],['Sellers',Store],['Brands',Store],['Products',ShoppingBag],['Categories',FileText],['Reels',Clapperboard],['Posts',FileText],['Advertisements',Image],['Orders',Package],['Payments',CreditCard],['Premium Plans',Crown],['Reviews',Star],['Reports',Flag],['Settings',Settings]] as const;
const field=(name:string,label:string,defaultValue:any='',type='text',required=true)=><label>{label}<input name={name} type={type} defaultValue={defaultValue??''} required={required} min={type==='number'?0:undefined}/></label>;
function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="table-wrap"><table className="data-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
function Status({value}:{value:string}){return <span className={`status ${value}`}>{value}</span>;}
function Upload({images,onChange}:{images:string[];onChange:(images:string[])=>void}){const {toast}=useStore();const [busy,setBusy]=useState(false);return <><label className="upload-area">{busy?'Uploading to your media library…':'Choose product photos · JPEG, PNG, WebP · Up to 5 MB each'}<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={async e=>{const files=Array.from(e.target.files||[]);if(files.length+images.length>8){toast('Choose up to 8 photos');return;}setBusy(true);try{const next=[...images];for(const file of files){if(file.size>5*1024*1024)throw new Error('Each image must be 5 MB or smaller');const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const r=await send('/upload',{mime:file.type,data});next.push(r.url);}onChange(next);}catch(e:any){toast(e.message);}finally{setBusy(false);}}}/></label><div className="upload-previews">{images.map((src,i)=><div className="upload-preview" key={src}><img src={src} alt={`Upload ${i+1}`}/><div><button type="button" aria-label={`Move image ${i+1} earlier`} disabled={i===0} onClick={()=>{const next=[...images];[next[i-1],next[i]]=[next[i],next[i-1]];onChange(next);}}>←</button><button type="button" aria-label={`Remove image ${i+1}`} onClick={()=>onChange(images.filter((_,j)=>i!==j))}>Remove</button></div></div>)}</div></>;}
export default function Dashboard({admin=false}:{admin?:boolean}){const {user,setLoginOpen,toast,refreshCatalog,config}=useStore();const [tab,setTab]=useState(admin?'Dashboard':'Overview'),[data,setData]=useState<any>(null),[error,setError]=useState(''),[modal,setModal]=useState<any>(null),[busy,setBusy]=useState(false),[images,setImages]=useState<string[]>([]);const tabs=admin?adminTabs:sellerTabs;async function load(){try{setData(await api(admin?'/admin':'/seller'));setError('');}catch(e:any){setError(e.message);}}useEffect(()=>{setTab(admin?'Dashboard':'Overview');if(user)void load();},[user?.id,admin]);async function act(url:string,payload:unknown={},method='PUT'){try{await send(url,payload,method);await load();await refreshCatalog();toast('Changes saved');return true;}catch(e:any){toast(e.message);return false;}}function open(type:string,item?:any){setImages([]);setModal({type,item});setError('');}async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget),s=(key:string)=>String(f.get(key)||''),n=(key:string)=>Number(f.get(key));try{
 if(modal.type==='product'){await send('/seller/products',{name:s('name'),description:s('description'),brand_id:s('brand_id'),category:s('category'),price:n('price'),original_price:n('original_price'),audience:s('audience'),status:s('status'),sizes:s('sizes').split(',').map(x=>x.trim()).filter(Boolean),colors:s('colors').split(',').map(x=>x.trim()).filter(Boolean),stock:n('stock'),images,external_url:s('external_url'),instagram:s('instagram'),video:s('video'),tags:s('tags').split(',').map(x=>x.trim()).filter(Boolean)});}
 if(modal.type==='edit-product'){await send(`/seller/products/${modal.item.id}`,{name:s('name'),description:s('description'),price:n('price'),original_price:n('original_price'),status:s('status')},'PUT');}
 if(modal.type==='brand'){const payload={name:s('name'),tagline:s('tagline'),description:s('description'),category:s('category'),website:s('website'),instagram:s('instagram'),image:images[0]||modal.item?.image||'',banner:images[1]||modal.item?.banner||''};await send('/seller/brands'+(modal.item?`/${modal.item.id}`:''),payload,modal.item?'PUT':'POST');}
 if(modal.type==='reel'){const product=data.products.find((p:any)=>p.id===s('product_id'));await send('/seller/reels',{brand_id:product?.brand_id,product_id:s('product_id'),caption:s('caption'),video:s('video'),image:images[0]||product?.image,status:s('status')});}
 if(modal.type==='post'){await send('/seller/posts',{brand_id:s('brand_id'),body:s('body'),image:images[0]||'',status:s('status')});}
 if(modal.type==='ad'){await send('/admin/advertisements',{title:s('title'),description:s('description'),image:images[0]||s('image'),video:s('video'),target_url:s('target_url'),brand_id:s('brand_id')||null,placement:s('placement'),status:s('status'),start_date:s('start_date')?new Date(s('start_date')).toISOString():null,end_date:s('end_date')?new Date(s('end_date')).toISOString():null});}
 if(modal.type==='plan'){await send(`/admin/plans/${modal.item.id}`,{price:s('price')===''?null:n('price'),product_limit:n('product_limit'),reel_limit:n('reel_limit')},'PUT');}
 if(modal.type==='category'){await send('/admin/categories',{name:s('name')});}
 setModal(null);await load();await refreshCatalog();toast('Saved. Your changes are ready.');
 }catch(e:any){setError(e.message);}finally{setBusy(false);}}
 if(!user)return <main className="page container"><Empty title={admin?'RACAN, behind the scenes.':'Your brand’s next chapter.'} description={admin?'Sign in with an administrator account to manage RACAN.':'Create your own corner of RACAN. Share your story, publish products, and find your community.'}/><div style={{textAlign:'center'}}><button className="btn" onClick={()=>setLoginOpen(true)}>Sign in to {admin?'admin':'seller studio'}</button></div></main>;
 if(admin?user.role!=='ADMIN':!['SELLER','ADMIN'].includes(user.role))return <main className="page container"><Empty title="This space is for our brand team." description="Use a seller account to access the studio, or an administrator account to manage the platform." to="/profile" label="Back to your profile"/></main>;
 const rows=admin?data?.[({Dashboard:'orders','Premium Plans':'premium_plans',Sellers:'users'} as Record<string,string>)[tab]||tab.toLowerCase()]:data?.[tab.toLowerCase()];const sales=data?.orders?.filter((o:any)=>o.status!=='Cancelled').reduce((sum:number,o:any)=>sum+(admin?o.total:o.price*o.quantity),0)||0;
 return <main className="dashboard"><aside className="dash-sidebar"><h2>{admin?'RACAN admin':'Your brand studio.'}</h2><p>{admin?'A thoughtful platform starts here.':'Big dreams. Beautiful beginnings.'}</p><nav>{tabs.map(([label,Icon])=><button className={tab===label?'active':''} key={label} onClick={()=>{setTab(label);setError('');}}><Icon size={16}/>{label}</button>)}</nav></aside><section className="dash-main"><div className="dash-head"><div><span className="eyebrow">{admin?'PLATFORM MANAGEMENT':'MADE FOR YOUR NEXT CHAPTER'}</span><h1>{tab==='Overview'?`Hello, ${user.name.split(' ')[0]}.`:tab}</h1><p>{tab==='Overview'?'Here’s what’s happening in your little corner of RACAN.':admin?'Keep the community and its discoveries in good hands.':'Create, connect, and grow your brand.'}</p></div>{!admin&&tab==='Products'&&<button className="btn" onClick={()=>open('product')}><Plus size={15}/>Add product</button>}{!admin&&tab==='Reels'&&<button className="btn" onClick={()=>open('reel')}><Plus size={15}/>Create Reel</button>}{!admin&&tab==='Posts'&&<button className="btn" onClick={()=>open('post')}><Plus size={15}/>Create post</button>}{!admin&&tab==='Brand'&&<button className="btn" onClick={()=>open('brand')}><Plus size={15}/>Create brand</button>}{admin&&tab==='Advertisements'&&<button className="btn" onClick={()=>open('ad')}><Plus size={15}/>New campaign</button>}{admin&&tab==='Categories'&&<button className="btn" onClick={()=>open('category')}><Plus size={15}/>Add category</button>}</div>{error&&!modal&&<div className="form-error">{error}</div>}{!data?<p className="loading-line">Opening your studio…</p>:<>
 {['Overview','Dashboard','Analytics'].includes(tab)&&<><div className="stat-grid">{[['Total sales',money(sales),'Excluding cancelled orders'],['Orders',new Set(data.orders.map((o:any)=>o.id)).size,'All time'],['Products',data.products.length,'In your catalog'],['Reel views',data.reels.reduce((s:number,r:any)=>s+r.views,0).toLocaleString(),'Seeded sample views']].map(([label,value,note])=><div className="stat-card" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div><div className="dashboard-card"><h2>A good place to grow.</h2><p>{admin?'Review new brands and products, manage campaigns, and follow every order from one place.':'Your products, your stories, your community. Keep your collection fresh and help people discover the thought behind every piece.'}</p><div className="inline-actions"><button className="btn secondary" onClick={()=>setTab('Products')}>Manage products<ArrowUpRight size={15}/></button><button className="btn secondary" onClick={()=>setTab(admin?'Brands':'Brand')}>Your brands<ArrowUpRight size={15}/></button></div></div>{tab==='Analytics'&&<div className="dashboard-card"><h2>Reel performance</h2><p>Views across your published sample stories.</p><div className="bar-chart">{data.reels.slice(0,8).map((r:any,i:number)=><div className="bar-column" key={r.id}><span style={{height:`${Math.max(3,r.views/18000*100)}%`}} title={`${r.views} views`}/><small>Reel {i+1}</small></div>)}</div></div>}<h2 style={{fontSize:27,marginBottom:20}}>Recent orders</h2>{data.orders.length?<Table headers={['Order','Status','Amount']}>{data.orders.slice(0,8).map((o:any,i:number)=><tr key={i}><td>{o.id}</td><td><Status value={o.status}/></td><td>{money(admin?o.total:o.price*o.quantity)}</td></tr>)}</Table>:<p style={{fontSize:12}}>Your first order will appear here. Every brand starts somewhere.</p>}</>}
 {tab==='Products'&&<Table headers={['Product','Price','Status','Actions']}>{data.products.filter((p:any)=>!p.deleted_at).map((p:any)=><tr key={p.id}><td><div className="table-product"><img src={p.image} alt=""/><span>{p.name}</span></div></td><td>{money(p.price)}</td><td><Status value={p.status}/></td><td><div className="table-actions">{admin?<><button onClick={()=>act('/admin/moderate',{entity:'products',id:p.id,status:'published'})}>Approve</button><button onClick={()=>act('/admin/moderate',{entity:'products',id:p.id,status:'rejected'})}>Reject</button></>:<><button onClick={()=>open('edit-product',p)}>Edit</button><button onClick={()=>{if(confirm(`Delete ${p.name} from your catalog?`))void act(`/seller/products/${p.id}`,{},'DELETE');}}>Delete</button></>}</div></td></tr>)}</Table>}
 {tab==='Inventory'&&<Table headers={['Product','Size / colour','SKU','Available','Update']}>{data.inventory.map((v:any)=><tr key={v.id}><td>{v.name}</td><td>{v.size} / {v.color}</td><td>{v.sku}</td><td>{v.quantity}</td><td><form className="table-actions" onSubmit={e=>{e.preventDefault();void act(`/seller/inventory/${v.id}`,{quantity:Number(new FormData(e.currentTarget).get('quantity'))});}}><input name="quantity" aria-label={`Stock for ${v.sku}`} type="number" min="0" max="10000" defaultValue={v.quantity}/><button>Save</button></form></td></tr>)}</Table>}
 {tab==='Orders'&&<Table headers={admin?['Order','Date','Total','Status','Next step']:['Order','Product','Quantity','Sales','Status']}>{data.orders.map((o:any,i:number)=><tr key={i}><td>{o.id}</td>{admin?<><td>{new Date(o.created_at).toLocaleDateString()}</td><td>{money(o.total)}</td><td><Status value={o.status}/></td><td><div className="table-actions">{['Confirmed','Processing','Shipped'].includes(o.status)&&<button onClick={()=>act(`/admin/orders/${o.id}`,{status:({Confirmed:'Processing',Processing:'Shipped',Shipped:'Delivered'} as Record<string,string>)[o.status]})}>Mark {({Confirmed:'processing',Processing:'shipped',Shipped:'delivered'} as Record<string,string>)[o.status]}</button>}</div></td></>:<><td>{o.name}</td><td>{o.quantity}</td><td>{money(o.price*o.quantity)}</td><td><Status value={o.status}/></td></>}</tr>)}</Table>}
 {tab==='Reels'&&<Table headers={['Story','Views','Likes','Status','Actions']}>{data.reels.filter((r:any)=>!r.deleted_at).map((r:any)=><tr key={r.id}><td><div className="table-product"><img src={r.image} alt=""/>{r.caption}</div></td><td>{r.views}</td><td>{r.likes}</td><td><Status value={r.status}/></td><td><div className="table-actions">{admin?<><button onClick={()=>act('/admin/moderate',{entity:'reels',id:r.id,status:'published'})}>Approve</button><button onClick={()=>act('/admin/moderate',{entity:'reels',id:r.id,status:'rejected'})}>Reject</button></>:<button onClick={()=>{if(confirm('Delete this Reel?'))void act(`/seller/reels/${r.id}`,{},'DELETE');}}>Delete</button>}</div></td></tr>)}</Table>}
 {tab==='Posts'&&<>{data.posts.length?<Table headers={['Post','Brand','Status']}>{data.posts.map((p:any)=><tr key={p.id}><td>{p.body}</td><td>{p.brand_id}</td><td><Status value={p.status}/></td></tr>)}</Table>:<Empty title="Tell the story behind your brand." description="Share a note, a new collection, or the little details that make your brand yours."/>}</>}
 {tab==='Brand'&&<>{data.brands.map((b:any)=><div className="dashboard-card" key={b.id}><div className="dash-head"><div><h2>{b.name}</h2><p>{b.tagline}</p></div><Status value={b.status}/></div><p>{b.description}</p><div className="inline-actions"><button className="btn secondary" onClick={()=>open('brand',b)}>Edit brand</button><Link className="btn secondary" to={`/brand/${b.id}`}>View storefront<ArrowUpRight size={15}/></Link></div></div>)}{!data.brands.length&&<Empty title="Start with your story." description="Create your brand profile to start uploading products and Reels."/>}</>}
 {tab==='Brands'&&admin&&<Table headers={['Brand','Category','Status','Moderation']}>{data.brands.map((b:any)=><tr key={b.id}><td>{b.name}</td><td>{b.category}</td><td><Status value={b.status}/></td><td><div className="table-actions"><button onClick={()=>act('/admin/moderate',{entity:'brands',id:b.id,status:'approved'})}>Approve</button><button onClick={()=>act('/admin/moderate',{entity:'brands',id:b.id,status:'rejected'})}>Reject</button></div></td></tr>)}</Table>}
 {['Users','Sellers'].includes(tab)&&admin&&<Table headers={['Name','Email','Role','Status','Action']}>{data.users.filter((u:any)=>tab!=='Sellers'||u.role==='SELLER').map((u:any)=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.role}</td><td>{u.disabled?'Disabled':'Active'}</td><td><div className="table-actions"><button disabled={u.id===user.id} onClick={()=>act(`/admin/users/${u.id}`,{disabled:!u.disabled})}>{u.disabled?'Enable':'Disable'}</button></div></td></tr>)}</Table>}
 {tab==='Premium'&&<><div className="notice">Plan prices are set by RACAN. Paid subscriptions become available when billing is configured.</div><div className="plan-grid">{data.plans.map((p:any)=><article className="plan-card" key={p.id}><span className="eyebrow">YOUR NEXT CHAPTER</span><h2>{p.name}</h2><div className="plan-price">{p.price===null?'Let’s talk':money(p.price)}</div><p>{p.price===0?'A beautiful place to begin.':p.price===null?'Pricing to be announced.':'per month · billing not yet available'}</p><ul>{p.features.map((f:string)=><li key={f}>{f}</li>)}</ul><button className="btn full secondary" disabled={data.subscription?.plan_id===p.id} onClick={()=>p.price===0?act('/seller/subscribe',{plan_id:p.id},'POST'):toast('Paid subscriptions are not yet available. Pricing and billing are managed by RACAN.')}>{data.subscription?.plan_id===p.id?'Your current plan':p.price===0?'Start free':'View availability'}</button></article>)}</div></>}
 {tab==='Premium Plans'&&admin&&<Table headers={['Plan','Price / month','Product limit','Reel limit','Action']}>{data.premium_plans.map((p:any)=><tr key={p.id}><td>{p.name}</td><td>{p.price===null?'Not configured':money(p.price)}</td><td>{p.product_limit}</td><td>{p.reel_limit}</td><td><div className="table-actions"><button onClick={()=>open('plan',p)}>Configure</button></div></td></tr>)}</Table>}
 {tab==='Advertisements'&&admin&&<Table headers={['Campaign','Placement','Schedule','Status','Action']}>{data.advertisements.map((a:any)=><tr key={a.id}><td>{a.title}</td><td>{a.placement}</td><td>{a.start_date?new Date(a.start_date).toLocaleDateString():'Always on'}</td><td><Status value={a.status}/></td><td><div className="table-actions"><button onClick={()=>act(`/admin/advertisements/${a.id}`,{status:a.status==='Active'?'Disabled':'Active'})}>{a.status==='Active'?'Disable':'Activate'}</button></div></td></tr>)}</Table>}
 {tab==='Categories'&&admin&&<div className="chips">{data.categories.map((c:any)=><span className="status" key={c.name}>{c.name}</span>)}</div>}
 {tab==='Payments'&&admin&&<Table headers={['Order','Amount','Provider','Status','Date']}>{data.payments.map((p:any)=><tr key={p.id}><td>{p.order_id}</td><td>{money(p.amount)}</td><td>{p.provider}</td><td><Status value={p.status}/></td><td>{new Date(p.created_at).toLocaleDateString()}</td></tr>)}</Table>}
 {tab==='Reviews'&&admin&&<Table headers={['Product','Rating','Review','Date']}>{data.reviews.map((r:any)=><tr key={r.id}><td>{r.product_id}</td><td>{r.rating} / 5</td><td>{r.body}</td><td>{new Date(r.created_at).toLocaleDateString()}</td></tr>)}</Table>}
 {tab==='Reports'&&admin&&<Table headers={['Reel','Reason','Status','Action']}>{data.reports.map((r:any)=><tr key={r.id}><td>{r.reel_id}</td><td>{r.reason}</td><td><Status value={r.status}/></td><td><div className="table-actions"><button onClick={()=>act('/admin/moderate',{entity:'reports',id:r.id,status:'resolved'})}>Resolve</button><button onClick={()=>act('/admin/moderate',{entity:'reports',id:r.id,status:'dismissed'})}>Dismiss</button></div></td></tr>)}</Table>}
 {tab==='Settings'&&(admin?<form className="form-grid" style={{maxWidth:500}} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('/admin/settings',{shipping:Number(f.get('shipping')),freeShippingThreshold:Number(f.get('threshold'))});}}>{field('shipping','Standard shipping (₹)',data.settings.find((s:any)=>s.key==='platform')?.value.shipping,'number')}{field('threshold','Free shipping threshold (₹)',data.settings.find((s:any)=>s.key==='platform')?.value.freeShippingThreshold,'number')}<button className="btn">Save platform settings</button></form>:<div className="dashboard-card"><h2>Your account</h2><p>{user.name}<br/>{user.email}<br/>Seller account</p><Link className="btn secondary" style={{marginTop:20}} to="/profile">Edit your profile<ArrowUpRight size={15}/></Link></div>)}
 </>}</section>{modal&&<Modal title={({product:'A new discovery', 'edit-product':'Refine your product',brand:modal.item?'Your brand, beautifully told':'Start your brand story',reel:'Create a shoppable story',post:'A note from your brand',ad:'A new campaign',plan:'Configure premium plan',category:'A new category'} as Record<string,string>)[modal.type]} onClose={()=>setModal(null)} wide={['product','brand','ad'].includes(modal.type)}><form className="form-grid" onSubmit={submit}>
 {['product','edit-product'].includes(modal.type)&&<>{field('name','Product name',modal.item?.name)}<label>Description<textarea name="description" defaultValue={modal.item?.description} required minLength={10} maxLength={3000}/></label><div className="form-row">{field('price','Selling price (₹)',modal.item?.price,'number')}{field('original_price','Original price (₹)',modal.item?.original_price,'number')}</div>{modal.type==='product'&&<><div className="form-row"><label>Brand<select aria-label="Brand" name="brand_id" required><option value="">Choose your brand</option>{data.brands.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Category<select aria-label="Category" name="category">{categories.filter(c=>c!=='All').map(c=><option key={c}>{c}</option>)}</select></label></div><div className="form-row">{field('sizes','Sizes, separated by commas','S,M,L')}{field('colors','Colours, separated by commas','Natural')}</div><div className="form-row">{field('stock','Stock per variant',10,'number')}<label>Audience<select name="audience"><option value="women">Women</option><option value="gen-z">Gen Z</option></select></label></div><label>Product photography</label><Upload images={images} onChange={setImages}/>{field('tags','Tags, separated by commas','','text',false)}{field('external_url','External product link','','url',false)}{field('instagram','Instagram link','','url',false)}{field('video','Product video URL','','url',false)}</>}<label>Publication status<select aria-label="Publication status" name="status" defaultValue={modal.item?.status==='draft'?'draft':'pending'}><option value="draft">Save as draft</option><option value="pending">Submit for approval</option></select></label><p className="form-note">Products are reviewed before they appear in the public catalog. SKU codes are generated for each size and colour combination.</p></>}
 {modal.type==='brand'&&<>{field('name','Brand name',modal.item?.name)}{field('tagline','Your brand in a sentence',modal.item?.tagline)}<label>Your story<textarea name="description" defaultValue={modal.item?.description} required minLength={10}/></label>{!modal.item&&<label>Category<select aria-label="Category" name="category">{categories.filter(c=>c!=='All').map(c=><option key={c}>{c}</option>)}</select></label>}{field('website','Website',modal.item?.website,'url',false)}{field('instagram','Instagram',modal.item?.instagram,'url',false)}<label>Brand logo and banner (in that order)</label><Upload images={images} onChange={setImages}/><p className="form-note">New brands and profile changes are reviewed by RACAN before publication.</p></>}
 {modal.type==='reel'&&<><label>Caption<textarea name="caption" required minLength={3} maxLength={500}/></label><label>Tag a product<select name="product_id" required>{data.products.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><VideoUpload/><label>Optional cover image</label><Upload images={images} onChange={setImages}/><label>Status<select aria-label="Publication status" name="status"><option value="draft">Draft</option><option value="pending">Submit for approval</option></select></label><p className="form-note">Use a video you own or have permission to publish. Product imagery is used as the cover if you do not upload one.</p></>}
 {modal.type==='post'&&<><label>Brand<select aria-label="Brand" name="brand_id">{data.brands.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Your note<textarea name="body" required minLength={3}/></label><Upload images={images} onChange={setImages}/><label>Status<select aria-label="Publication status" name="status"><option value="draft">Draft</option><option value="published">Publish</option></select></label></>}
 {modal.type==='ad'&&<>{field('title','Campaign title')}<label>Description<textarea name="description" required/></label><Upload images={images} onChange={setImages}/>{!images.length&&field('image','Or use a local image path','/images/hero.jpg')}{field('video','Video URL','','url',false)}{field('target_url','Destination URL or path','/explore')}<label>Brand<select aria-label="Brand" name="brand_id"><option value="">Platform campaign</option>{data.brands.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><div className="form-row"><label>Placement<select name="placement">{['Landing Top','Landing Middle','Gen Z','Women','Reels','Other'].map(p=><option key={p}>{p}</option>)}</select></label><label>Status<select aria-label="Publication status" name="status">{['Draft','Active','Expired','Disabled'].map(s=><option key={s}>{s}</option>)}</select></label></div><div className="form-row">{field('start_date','Starts','','datetime-local',false)}{field('end_date','Ends','','datetime-local',false)}</div></>}
 {modal.type==='plan'&&<>{field('price','Monthly price (₹), leave empty for unconfigured',modal.item.price,'number',false)}{field('product_limit','Product limit',modal.item.product_limit,'number')}{field('reel_limit','Reel limit',modal.item.reel_limit,'number')}<p className="form-note">Prices are display configuration. Paid subscriptions require a configured billing provider.</p></>}
 {modal.type==='category'&&field('name','Category name')}{error&&<div className="form-error" role="alert">{error}</div>}<button className="btn" disabled={busy}>{busy?'Saving…':'Save changes'}<ArrowUpRight size={16}/></button></form></Modal>}</main>;
}
