import {useState} from 'react';
import {BannerCarousel} from '../components/BannerCarousel';
import {Link} from 'react-router-dom';
import {ArrowRight,ArrowUpRight,ChevronLeft,ChevronRight,Play,Sparkles,Heart,Pause,MoreHorizontal} from 'lucide-react';
import {useStore} from '../lib/store';
import {BrandCard,ProductCard,ReelCard,SectionHead} from '../components/ui';
export default function Home(){const {catalog}=useStore();const [filter,setFilter]=useState('For you');const ads=catalog.ads.filter((a:any)=>a.placement==='Landing Top');const campaign=catalog.ads.find((a:any)=>a.placement==='Landing Middle');const picks=filter==='New arrivals'?[...catalog.products].reverse():filter==='Most loved'?[...catalog.products].sort((a:any,b:any)=>Number(b.rating)-Number(a.rating)):['p1','p2','p3','p5'].map(id=>catalog.products.find((p:any)=>p.id===id)).filter(Boolean);return <main>
 <BannerCarousel ads={ads}/>
 <section className="category-strip container" aria-label="Shop categories">{[['Fashion','dress'],['Bags','bag'],['Jewellery','jewel'],['Beauty','beauty'],['Accessories','top'],['More','more']].map(([label,img])=><Link to={`/explore?category=${label==='Fashion'?'Dresses':label}`} key={label}><span className="category-icon">{img==='more'?<MoreHorizontal size={21}/>:<img src={`/images/${img}.jpg`} alt=""/>}</span><b>{label}</b></Link>)}</section>
 <section className="brand-cta container"><div><span className="eyebrow">BUILD SOMETHING BEAUTIFUL</span><h2>Add your brand.</h2><p>Showcase your work, tell your story, and grow with a community that gets it.</p><Link className="btn" to="/seller/dashboard">Get started <ArrowUpRight size={16}/></Link></div><img src="/images/bag.jpg" alt="A collection from an independent brand"/><div className="brand-cta-sticker">YOUR STORY<br/><b>✳</b><br/>STARTS HERE</div></section>
 <section className="worlds container"><div className="worlds-intro"><span className="eyebrow">TWO WORLDS. ENDLESS POSSIBILITIES.</span><h2>Your style.<br/><em>Your world.</em></h2><p>Different moods. Same main character.<br/>Find the edit that feels like you.</p></div><Link className="world-card genz-world" to="/gen-z"><div className="world-circle"><img src="/images/street.jpg" alt="Expressive Gen Z street style"/><span className="circle-sticker">NO RULES.<br/>JUST YOU.</span><span className="circle-arrow"><ArrowUpRight/></span></div><div className="world-label"><h3>Gen Z <span>✦</span></h3><p>Big energy. Fresh perspectives.</p></div></Link><Link className="world-card women-world" to="/women"><div className="world-circle"><img src="/images/dress.jpg" alt="Elegant contemporary womenswear"/><span className="circle-arrow"><ArrowUpRight/></span></div><div className="world-label"><h3>Women</h3><p>Effortless style. Every version of you.</p></div></Link><span className="world-doodle">✳</span></section>
 <section className="section container"><SectionHead eyebrow="THE NAMES YOU’LL WANT TO KNOW" title="Small brands. Big love." subtitle="Independent labels, beautiful stories. Meet your next obsession." to="/brands" label="Meet all brands"/><div className="brand-grid home-brands">{['suta','summer','the-label-life','okhai','nori','palmonas'].map(id=>catalog.brands.find((b:any)=>b.id===id)).filter(Boolean).map((b:any)=><BrandCard key={b.id} brand={b}/>)}</div></section>
 {campaign&&<section className="campaign container"><div className="campaign-copy"><span className="eyebrow"><Heart size={13}/> HER VISION. YOUR NEXT FAVOURITE.</span><h2>{campaign.id==='ad3'?<>Good things<br/>come <em>from her.</em></>:campaign.title}</h2><p>{campaign.description}</p><Link to={campaign.target_url} className="text-link">Explore independent brands<ArrowUpRight size={18}/></Link></div><div className="campaign-image"><img src={campaign.image} alt={campaign.title}/><span>made with intention.</span></div><div className="campaign-quote"><span>“</span><p>More than a label.<br/>A little piece<br/>of someone’s dream.</p><small>THE RACAN BRAND EDIT — 01</small><span className="campaign-flower">✳</span></div></section>}
 <section className="section container"><SectionHead eyebrow="CURRENTLY IN EVERYONE’S SAVES" title="A little too good to scroll past." to="/explore" label="Shop the edit"/><div className="filter-tabs" role="tablist" aria-label="Product selection">{['For you','New arrivals','Most loved'].map(t=><button key={t} role="tab" aria-selected={filter===t} className={filter===t?'active':''} onClick={()=>setFilter(t)}>{t}{t==='For you'&&<Sparkles size={13}/>}</button>)}<span>Thoughtfully picked. Endlessly wearable.</span></div><div className="product-grid">{picks.slice(0,4).map((p:any)=><ProductCard key={p.id} product={p}/>)}</div></section>
 <section className="reels-preview"><div className="container"><SectionHead eyebrow="SEE IT. LOVE IT. MAKE IT YOURS." title="Real style. On repeat." subtitle="Outfit inspiration, everyday stories, and a little ‘where did you get that?’" to="/reels" label="Enter RACAN Reels"/><div className="reel-grid">{catalog.reels.slice(0,5).map((r:any)=><ReelCard key={r.id} reel={r}/>)}</div><div className="reels-note"><Play size={15} fill="currentColor"/><span>A new way to discover. A more you way to shop.</span><Link to="/reels">Find your inspiration <ArrowRight size={16}/></Link></div></div></section>
 </main>;}
