import {useEffect,useRef,type ReactNode} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,Heart,Star,Play,ArrowRight,X,ShoppingBag,Check} from 'lucide-react';
import {useStore} from '../lib/store';
import {money} from '../lib/api';
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=ref.current!;el.showModal();const previous=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;previous?.focus();};},[]);return <dialog ref={ref} className={`modal ${wide?'wide':''}`} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" aria-label="Close dialog" onClick={onClose}><X/></button></div>{children}</dialog>;}
export function SectionHead({eyebrow,title,subtitle,to,label='Explore all'}:{eyebrow?:string;title:string;subtitle?:string;to?:string;label?:string}){return <div className="section-head"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{to&&<Link className="text-link" to={to}>{label}<ArrowUpRight size={17}/></Link>}</div>;}
export function ProductCard({product:p}:{product:any}){const {wishlist,my}=useStore();return <article className="product-card"><div className="product-image"><Link to={`/product/${p.id}`}><img src={p.image} alt={p.name} loading="lazy"/></Link>{p.badge&&<span className="product-badge">{p.badge}</span>}<button className={`save-btn ${my.wishlist.includes(p.id)?'saved':''}`} aria-label={`Save ${p.name}`} aria-pressed={my.wishlist.includes(p.id)} onClick={()=>wishlist(p.id)}><Heart size={18}/></button><Link className="quick-shop" to={`/product/${p.id}`}><ShoppingBag size={16}/> Choose your style <ArrowRight size={16}/></Link></div><div className="product-meta"><Link to={`/brand/${p.brand_id}`}>{p.brand_name||p.brand_id}</Link><span><Star size={12} fill="currentColor"/>{Number(p.rating).toFixed(1)}</span></div><Link className="product-name" to={`/product/${p.id}`}>{p.name}</Link><div className="price">{money(p.price)}{p.original_price>p.price&&<><del>{money(p.original_price)}</del><span>{Math.round((1-p.price/p.original_price)*100)}% off</span></>}</div></article>;}
export function BrandCard({brand:b}:{brand:any}){return <Link className="brand-card" to={`/brand/${b.id}`}><div className={`brand-tile brand-${b.id}`} style={{background:b.color,color:b.ink}}>{b.image?<img src={b.image} alt={b.name}/>:<span>{b.name}</span>}<ArrowUpRight size={19}/></div><h3>{b.name}{b.verified&&<span className="verified"><Check size={10}/></span>}</h3><p>{b.tagline}</p></Link>;}
export function ReelCard({reel:r}:{reel:any}){return <Link to={`/reels?id=${r.id}`} className="reel-card"><img src={r.image} alt={`${r.creator} styling ${r.brand_name||r.brand_id}`} loading="lazy"/><span className="reel-play"><Play size={16} fill="currentColor"/>{(r.views/1000).toFixed(1)}k</span><div className="reel-card-info"><span className="mini-avatar">{r.creator?.[0]}</span><span><b>{r.creator}</b><small>{r.caption}</small></span><ArrowUpRight size={18}/></div><span className="reel-shop"><ShoppingBag size={13}/>Shop the look</span></Link>;}
export function Empty({title,description,to,label='Start discovering'}:{title:string;description:string;to?:string;label?:string}){return <div className="empty"><span className="empty-icon"><ShoppingBag size={32}/></span><h2>{title}</h2><p>{description}</p>{to&&<Link className="btn" to={to}>{label}<ArrowRight size={16}/></Link>}</div>;}
export function Loading(){return <div className="container loading-grid" aria-label="Loading RACAN">{Array.from({length:8},(_,i)=><div className="skeleton" key={i}/>)}</div>;}
