import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const errors=[];
async function session(role){const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:3000');await page.getByRole('button',{name:'Your profile',exact:true}).click();await page.getByRole('button',{name:role,exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});return page;}
try{
const shopper=await session('Shopper');
await shopper.goto('http://127.0.0.1:3000/product/p1');await shopper.getByRole('button',{name:'Add to bag',exact:true}).click();await shopper.getByRole('status').filter({hasText:'added to your bag'}).waitFor();
await shopper.goto('http://127.0.0.1:3000/checkout');await shopper.getByLabel('Phone number').fill('9876543210');await shopper.getByLabel('Delivery address').fill('123 Test Avenue, Development Test Area');await shopper.getByLabel('City',{exact:true}).fill('Mumbai');await shopper.getByLabel('PIN code').fill('400001');await shopper.getByRole('button',{name:'Place development order'}).click();await shopper.waitForURL('**/orders?new=*');await shopper.getByText('Confirmed',{exact:true}).first().waitFor();await shopper.screenshot({path:'artifacts/order-confirmation.png',fullPage:true});
shopper.on('dialog',dialog=>dialog.accept());await shopper.getByRole('button',{name:'Cancel order',exact:true}).first().click();await shopper.getByText('This order was cancelled.',{exact:true}).first().waitFor();console.log('Shopper checkout and cancellation: PASS');
const seller=await session('Seller');await seller.goto('http://127.0.0.1:3000/seller/dashboard');await seller.getByRole('button',{name:'Products',exact:true}).click();await seller.getByRole('button',{name:'Add product',exact:true}).click();const productName='Browser QA Cotton Dress '+Date.now();await seller.getByLabel('Product name',{exact:true}).fill(productName);await seller.getByLabel('Description',{exact:true}).fill('A browser verification product for the seller submission and moderation journey.');await seller.getByLabel('Selling price').fill('1290');await seller.getByLabel('Original price').fill('1590');await seller.getByLabel('Brand',{exact:true}).selectOption('summer');await seller.getByLabel('Category',{exact:true}).selectOption('Dresses');await seller.locator('input[type=file]').setInputFiles('public/images/dress.jpg');await seller.getByRole('img',{name:'Upload 1',exact:true}).waitFor();await seller.getByLabel('Publication status').selectOption('pending');await seller.getByRole('button',{name:'Save changes',exact:true}).click();await seller.getByRole('dialog').waitFor({state:'hidden'});await seller.getByText(productName,{exact:true}).waitFor();await seller.screenshot({path:'artifacts/seller-products.png',fullPage:true});console.log('Seller image upload and product submission: PASS');
const admin=await session('Admin');await admin.goto('http://127.0.0.1:3000/admin');await admin.getByRole('button',{name:'Products',exact:true}).click();const row=admin.getByRole('row').filter({hasText:productName});await row.getByRole('button',{name:'Approve',exact:true}).click();await row.getByText('published',{exact:true}).waitFor();await admin.screenshot({path:'artifacts/admin-products.png',fullPage:true});
await shopper.goto('http://127.0.0.1:3000/explore?q='+encodeURIComponent(productName));await shopper.getByRole('link',{name:productName,exact:true}).first().waitFor();console.log('Admin approval and public discovery: PASS');
// Remove the QA listing after verifying publication, keeping catalog fixtures tidy.
await seller.reload();await seller.getByRole('button',{name:'Products',exact:true}).click();seller.on('dialog',dialog=>dialog.accept());await seller.getByRole('row').filter({hasText:productName}).getByRole('button',{name:'Delete',exact:true}).click();await seller.getByRole('row').filter({hasText:productName}).waitFor({state:'detached'});
await shopper.goto('http://127.0.0.1:3000/reels?id=r1');await shopper.locator('video').waitFor();await shopper.waitForFunction(()=>{const v=document.querySelector('video');return v&&v.readyState>=2&&!v.paused;},{},{timeout:20000});const time=await shopper.locator('video').evaluate(v=>v.currentTime);assert.ok(time>=0);await shopper.getByRole('button',{name:'Like Reel',exact:true}).click();await shopper.getByRole('button',{name:'View comments',exact:true}).click();await shopper.getByLabel('Leave a comment').fill('A lovely find — browser journey verified.');await shopper.getByRole('button',{name:'Post comment',exact:true}).click();await shopper.getByText('A lovely find — browser journey verified.',{exact:true}).last().waitFor();console.log('Video playback, liking, commenting: PASS');
await shopper.getByRole('button',{name:'Close dialog'}).click();await shopper.setViewportSize({width:390,height:844});await shopper.screenshot({path:'artifacts/reels-mobile.png',fullPage:true});assert.equal(await shopper.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);console.log('Mobile Reels overflow: PASS');
assert.deepEqual(errors,[]);console.log('Browser runtime errors: none');
}catch(error){for(const [i,context] of browser.contexts().entries()){for(const page of context.pages()){await page.screenshot({path:'artifacts/journey-failure-'+i+'.png',fullPage:true}).catch(()=>{});console.log('Failure page',await page.url(),(await page.locator('body').innerText()).slice(-4000));}}throw error;}finally{await browser.close();}
