import {Router,type RequestHandler} from 'express';
import {rateLimit} from 'express-rate-limit';
import {hash,compare} from 'bcryptjs';
import {randomBytes,createHash,randomUUID} from 'node:crypto';
import {z} from 'zod';
import {db,transaction} from '../db/index.ts';
import {assert} from '../lib/errors.ts';
declare global {namespace Express {interface Request {user?:{id:string;name:string;email:string;role:string}}}}
const digest=(token:string)=>createHash('sha256').update(token).digest('hex');
export const identify:RequestHandler=async(req,_res,next)=>{try{if(req.cookies.racan_session){const {rows}=await db.query('SELECT u.id,u.name,u.email,u.role FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token_hash=$1 AND s.expires_at>now() AND NOT u.disabled AND u.deleted_at IS NULL',[digest(req.cookies.racan_session)]);req.user=rows[0];}next();}catch(e){next(e);}};
export const requireUser:RequestHandler=(req,_res,next)=>{assert(req.user,401,'Sign in to continue');next();};
export const role=(...roles:string[]):RequestHandler=>(req,_res,next)=>{assert(req.user,401,'Sign in to continue');assert(roles.includes(req.user.role),403,'You do not have access to this area');next();};
export const auth=Router();
auth.use(rateLimit({windowMs:15*60*1000,limit:80,standardHeaders:'draft-7',legacyHeaders:false}));
async function session(res:any,user:any){const token=randomBytes(32).toString('base64url');await db.query("INSERT INTO sessions VALUES($1,$2,now()+interval '7 days')",[digest(token),user.id]);res.cookie('racan_session',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000,path:'/'});return {id:user.id,name:user.name,email:user.email,role:user.role};}
auth.get('/me',(req,res)=>res.json(req.user||null));
auth.post('/register',async(req,res)=>{const v=z.object({name:z.string().min(2).max(80),email:z.string().email().max(254).transform(s=>s.toLowerCase()),password:z.string().min(10).max(128),seller:z.boolean().optional()}).parse(req.body);assert(!(await db.query('SELECT id FROM users WHERE email=$1',[v.email])).rows.length,409,'This email is already registered');const u={id:randomUUID(),name:v.name,email:v.email,role:v.seller?'SELLER':'USER'};const ph=await hash(v.password,12);await transaction(async tx=>{await tx.query('INSERT INTO users(id,name,email,password_hash,role) VALUES($1,$2,$3,$4,$5)',[u.id,u.name,u.email,ph,u.role]);await tx.query('INSERT INTO profiles(user_id) VALUES($1)',[u.id]);});res.status(201).json(await session(res,u));});
auth.post('/login',async(req,res)=>{const v=z.object({email:z.string().email(),password:z.string().max(128)}).parse(req.body);const u=(await db.query('SELECT * FROM users WHERE email=$1 AND NOT disabled AND deleted_at IS NULL',[v.email.toLowerCase()])).rows[0];assert(u&&await compare(v.password,u.password_hash),401,'Email or password is incorrect');res.json(await session(res,u));});
auth.post('/demo',async(req,res)=>{assert(process.env.NODE_ENV!=='production',404,'Not found');const r=z.enum(['user','seller','admin']).parse(req.body.role);const u=(await db.query('SELECT * FROM users WHERE id=$1',[`demo-${r}`])).rows[0];res.json(await session(res,u));});
auth.post('/logout',async(req,res)=>{if(req.cookies.racan_session)await db.query('DELETE FROM sessions WHERE token_hash=$1',[digest(req.cookies.racan_session)]);res.clearCookie('racan_session',{path:'/'}).json({ok:true});});
auth.post('/forgot',async(req,res)=>{const {email}=z.object({email:z.string().email()}).parse(req.body);assert(process.env.NODE_ENV!=='production',503,'Password reset is temporarily unavailable. Please contact support.');const u=(await db.query('SELECT id FROM users WHERE email=$1',[email.toLowerCase()])).rows[0];let resetUrl;if(u){const token=randomBytes(32).toString('base64url');await db.query("INSERT INTO password_resets VALUES($1,$2,now()+interval '30 minutes',false)",[digest(token),u.id]);if(process.env.NODE_ENV!=='production')resetUrl=`/reset-password?token=${token}`;else throw new Error('Transactional email adapter is not configured');}res.json({message:'If the account exists, a password reset has been requested.',resetUrl});});
auth.post('/reset',async(req,res)=>{const v=z.object({token:z.string().min(32),password:z.string().min(10).max(128)}).parse(req.body);const ph=await hash(v.password,12);await transaction(async tx=>{const t=(await tx.query('UPDATE password_resets SET used=true WHERE token_hash=$1 AND expires_at>now() AND NOT used RETURNING user_id',[digest(v.token)])).rows[0];assert(t,400,'This reset link is invalid or expired');await tx.query('UPDATE users SET password_hash=$1 WHERE id=$2',[ph,t.user_id]);await tx.query('DELETE FROM sessions WHERE user_id=$1',[t.user_id]);});res.json({ok:true});});
