import {Router} from 'express';
import {z} from 'zod';
import {db} from '../db/index.ts';
import {assert} from '../lib/errors.ts';
export const catalog=Router();
export const productSelect=`SELECT p.*, b.name AS brand_name, (SELECT json_agg(json_build_object('id',v.id,'size',v.size,'color',v.color,'stock',i.quantity) ORDER BY v.size) FROM product_variants v JOIN inventory i ON i.variant_id=v.id WHERE v.product_id=p.id) AS variants FROM products p JOIN brands b ON b.id=p.brand_id`;
catalog.get('/catalog',async(req,res)=>{
 const v=z.object({q:z.string().max(100).default(''),category:z.string().max(80).default('All'),audience:z.string().max(20).default(''),brand:z.string().max(100).default(''),sort:z.enum(['trending','price-low','price-high','newest']).default('trending'),page:z.coerce.number().int().min(1).max(1000).default(1),limit:z.coerce.number().int().min(1).max(60).default(36)}).parse(req.query);
 const params=[`%${v.q}%`,v.category,v.audience,v.brand];const where=` WHERE p.status='published' AND p.deleted_at IS NULL AND b.status='approved' AND b.deleted_at IS NULL AND (p.name ILIKE $1 OR b.name ILIKE $1 OR p.category ILIKE $1) AND ($2='All' OR p.category=$2) AND ($3='' OR p.audience=$3) AND ($4='' OR p.brand_id=$4)`;
 const order={trending:'p.rating DESC', 'price-low':'p.price ASC','price-high':'p.price DESC',newest:'p.created_at DESC'}[v.sort];
 const [p,b,r,a,plans,c]=await Promise.all([db.query(productSelect+where+` ORDER BY ${order},p.id LIMIT $5 OFFSET $6`,[...params,v.limit,(v.page-1)*v.limit]),db.query("SELECT b.*,(SELECT count(*)::int FROM brand_followers f WHERE f.brand_id=b.id) AS followers FROM brands b WHERE status='approved' AND deleted_at IS NULL ORDER BY created_at,id"),db.query("SELECT r.*,(r.likes+(SELECT count(*)::int FROM reel_likes l WHERE l.reel_id=r.id)) AS likes,b.name AS brand_name FROM reels r JOIN brands b ON b.id=r.brand_id WHERE r.status='published' AND r.deleted_at IS NULL AND b.status='approved' ORDER BY r.id LIMIT 30"),db.query("SELECT * FROM advertisements WHERE status='Active' AND (start_date IS NULL OR start_date<=now()) AND (end_date IS NULL OR end_date>now())"),db.query('SELECT * FROM premium_plans ORDER BY product_limit'),db.query('SELECT count(*)::int AS total FROM products p JOIN brands b ON b.id=p.brand_id'+where,params)]);
 res.json({products:p.rows,brands:b.rows,reels:r.rows,ads:a.rows,plans:plans.rows,total:c.rows[0].total,page:v.page});
});
catalog.get('/products/:id',async(req,res)=>{const p=(await db.query(productSelect+" WHERE p.id=$1 AND p.status='published' AND p.deleted_at IS NULL AND b.status='approved'",[req.params.id])).rows[0];assert(p,404,'Product not found');p.images=(await db.query('SELECT * FROM product_images WHERE product_id=$1 ORDER BY position',[p.id])).rows;p.reviews=(await db.query('SELECT r.*,u.name FROM reviews r JOIN users u ON u.id=r.user_id WHERE product_id=$1 ORDER BY created_at DESC LIMIT 30',[p.id])).rows;res.json(p);});
catalog.get('/brands/:id/posts',async(req,res)=>res.json((await db.query("SELECT p.* FROM posts p JOIN brands b ON b.id=p.brand_id WHERE b.id=$1 AND b.status='approved' AND p.status='published' ORDER BY p.created_at DESC LIMIT 30",[req.params.id])).rows));
catalog.get('/creators/:id',async(req,res)=>{const u=(await db.query("SELECT u.id,u.name,p.bio,p.image,(SELECT count(*)::int FROM follows WHERE following_id=u.id) AS followers FROM users u LEFT JOIN profiles p ON p.user_id=u.id WHERE u.id=$1 AND u.role='SELLER' AND NOT u.disabled AND u.deleted_at IS NULL",[req.params.id])).rows[0];assert(u,404,'Creator not found');u.brands=(await db.query("SELECT * FROM brands WHERE owner_id=$1 AND status='approved' AND deleted_at IS NULL",[u.id])).rows;u.reels=(await db.query("SELECT r.*,(r.likes+(SELECT count(*)::int FROM reel_likes l WHERE l.reel_id=r.id)) AS likes,b.name AS brand_name FROM reels r JOIN brands b ON b.id=r.brand_id WHERE b.owner_id=$1 AND b.status='approved' AND r.status='published' AND r.deleted_at IS NULL LIMIT 30",[u.id])).rows;res.json(u);});
catalog.get('/search',async(req,res)=>{const q=z.string().min(1).max(100).parse(req.query.q);const term=`%${q}%`;const [products,brands,reels,creators,categories]=await Promise.all([db.query("SELECT p.id,p.name,p.image,b.name AS brand_name FROM products p JOIN brands b ON b.id=p.brand_id WHERE p.status='published' AND p.deleted_at IS NULL AND b.status='approved' AND (p.name ILIKE $1 OR p.category ILIKE $1 OR b.name ILIKE $1) LIMIT 6",[term]),db.query("SELECT id,name FROM brands WHERE status='approved' AND deleted_at IS NULL AND name ILIKE $1 LIMIT 4",[term]),db.query("SELECT r.id,r.caption,r.image,r.creator FROM reels r JOIN brands b ON b.id=r.brand_id WHERE r.status='published' AND r.deleted_at IS NULL AND b.status='approved' AND (r.caption ILIKE $1 OR r.creator ILIKE $1 OR b.name ILIKE $1) LIMIT 4",[term]),db.query("SELECT id,name FROM users WHERE role='SELLER' AND NOT disabled AND deleted_at IS NULL AND name ILIKE $1 LIMIT 4",[term]),db.query('SELECT name FROM categories WHERE name ILIKE $1 LIMIT 5',[term])]);res.json({products:products.rows,brands:brands.rows,reels:reels.rows,creators:creators.rows,categories:categories.rows});});
