import {Router} from 'express';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {db,transaction} from '../db/index.ts';
import {requireUser} from './auth.ts';
import {assert} from '../lib/errors.ts';
import {paymentProvider} from './payments.ts';
export const commerce=Router();commerce.use(requireUser);
export const cartSQL=`SELECT c.variant_id,c.quantity,v.size,v.color,i.quantity AS stock,p.id AS product_id,p.name,p.price,p.image,p.brand_id,b.name AS brand_name,p.status,p.deleted_at,b.status AS brand_status FROM cart_items c JOIN product_variants v ON v.id=c.variant_id JOIN inventory i ON i.variant_id=v.id JOIN products p ON p.id=v.product_id JOIN brands b ON b.id=p.brand_id WHERE c.cart_id=$1 ORDER BY c.variant_id`;
commerce.get('/cart',async(req,res)=>res.json((await db.query(cartSQL,[req.user!.id])).rows));
commerce.put('/cart',async(req,res)=>{const v=z.object({variant_id:z.string().max(150),quantity:z.number().int().min(0).max(20)}).parse(req.body);await transaction(async tx=>{await tx.query('INSERT INTO carts(id,user_id) VALUES($1,$1) ON CONFLICT DO NOTHING',[req.user!.id]);if(!v.quantity){await tx.query('DELETE FROM cart_items WHERE cart_id=$1 AND variant_id=$2',[req.user!.id,v.variant_id]);return;}const stock=(await tx.query("SELECT i.quantity FROM inventory i JOIN product_variants v ON v.id=i.variant_id JOIN products p ON p.id=v.product_id JOIN brands b ON b.id=p.brand_id WHERE v.id=$1 AND p.status='published' AND p.deleted_at IS NULL AND b.status='approved'",[v.variant_id])).rows[0];assert(stock&&stock.quantity>=v.quantity,409,'This quantity is no longer available');await tx.query('INSERT INTO cart_items VALUES($1,$2,$3) ON CONFLICT(cart_id,variant_id) DO UPDATE SET quantity=$3',[req.user!.id,v.variant_id,v.quantity]);});res.json({ok:true});});
export const checkoutSchema=z.object({key:z.string().uuid(),address:z.object({name:z.string().min(2).max(100),phone:z.string().regex(/^[6-9]\d{9}$/,'Enter a valid 10-digit Indian phone number'),line:z.string().min(8).max(300),city:z.string().min(2).max(80),pincode:z.string().regex(/^\d{6}$/,'Enter a 6-digit PIN code')})});
commerce.post('/checkout',async(req,res)=>{const v=checkoutSchema.parse(req.body);const provider=paymentProvider();const order=await transaction(async tx=>{
 // A per-user row lock serializes concurrent checkouts before reading the cart.
 await tx.query('SELECT id FROM users WHERE id=$1 FOR UPDATE',[req.user!.id]);
 const old=(await tx.query('SELECT * FROM orders WHERE user_id=$1 AND idempotency_key=$2',[req.user!.id,v.key])).rows[0];if(old)return old;
 const items=(await tx.query(cartSQL,[req.user!.id])).rows;assert(items.length,400,'Your bag is empty');
 let subtotal=0;for(const item of items){assert(item.status==='published'&&!item.deleted_at&&item.brand_status==='approved',409,`${item.name} is no longer available`);const updated=await tx.query('UPDATE inventory SET quantity=quantity-$1,updated_at=now() WHERE variant_id=$2 AND quantity>=$1 RETURNING quantity',[item.quantity,item.variant_id]);assert(updated.rows.length,409,`${item.name} has insufficient stock`);subtotal+=item.price*item.quantity;}
 const settings=(await tx.query("SELECT value FROM settings WHERE key='platform'")).rows[0].value;const shipping=subtotal>=settings.freeShippingThreshold?0:settings.shipping;const total=subtotal+shipping;const id='RC-'+randomUUID().slice(0,8).toUpperCase();
 const payment=await provider.authorize(total);
 await tx.query('INSERT INTO orders(id,user_id,total,shipping,address,idempotency_key) VALUES($1,$2,$3,$4,$5,$6)',[id,req.user!.id,total,shipping,JSON.stringify(v.address),v.key]);
 for(const i of items)await tx.query('INSERT INTO order_items(id,order_id,product_id,variant_id,brand_id,name,image,variant,price,quantity) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[randomUUID(),id,i.product_id,i.variant_id,i.brand_id,i.name,i.image,`${i.size} / ${i.color}`,i.price,i.quantity]);
 await tx.query('INSERT INTO payments(id,order_id,provider,amount,status,reference) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),id,provider.name,total,payment.status,payment.reference]);
 await tx.query('DELETE FROM cart_items WHERE cart_id=$1',[req.user!.id]);await tx.query('INSERT INTO notifications(id,user_id,message) VALUES($1,$2,$3)',[randomUUID(),req.user!.id,`Your order ${id} is confirmed. Thank you for discovering with RACAN.`]);return {id,total};
 });res.status(201).json(order);});
commerce.get('/orders',async(req,res)=>res.json((await db.query('SELECT o.*,p.status AS payment_status,p.provider,(SELECT json_agg(i.*) FROM order_items i WHERE i.order_id=o.id) AS items FROM orders o JOIN payments p ON p.order_id=o.id WHERE o.user_id=$1 ORDER BY o.created_at DESC',[req.user!.id])).rows));
commerce.post('/orders/:id/cancel',async(req,res)=>{await transaction(async tx=>{const o=(await tx.query('SELECT * FROM orders WHERE id=$1 AND user_id=$2 FOR UPDATE',[req.params.id,req.user!.id])).rows[0];assert(o,404,'Order not found');assert(['Pending','Confirmed'].includes(o.status),409,'This order can no longer be cancelled');assert((await tx.query('SELECT provider FROM payments WHERE order_id=$1',[o.id])).rows[0].provider==='development',409,'Contact support for a refund');await tx.query("UPDATE orders SET status='Cancelled' WHERE id=$1",[o.id]);await tx.query("UPDATE payments SET status='Refunded' WHERE order_id=$1",[o.id]);for(const i of (await tx.query('SELECT * FROM order_items WHERE order_id=$1',[o.id])).rows)await tx.query('UPDATE inventory SET quantity=quantity+$1 WHERE variant_id=$2',[i.quantity,i.variant_id]);});res.json({ok:true});});
