CREATE TABLE IF NOT EXISTS roles (name text PRIMARY KEY);
INSERT INTO roles VALUES ('USER'),('SELLER'),('ADMIN') ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY,email text UNIQUE NOT NULL,password_hash text NOT NULL,name text NOT NULL,role text REFERENCES roles(name) DEFAULT 'USER',disabled boolean DEFAULT false,created_at timestamptz DEFAULT now(),deleted_at timestamptz);
CREATE TABLE IF NOT EXISTS profiles (user_id text PRIMARY KEY REFERENCES users(id),bio text DEFAULT '',image text);
CREATE TABLE IF NOT EXISTS sessions (token_hash text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS password_resets (token_hash text PRIMARY KEY,user_id text REFERENCES users(id),expires_at timestamptz NOT NULL,used boolean DEFAULT false);
CREATE TABLE IF NOT EXISTS categories (name text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS brands (id text PRIMARY KEY,owner_id text REFERENCES users(id),name text NOT NULL,tagline text,description text DEFAULT '',category text REFERENCES categories(name),color text,ink text,image text,banner text,website text,instagram text,verified boolean DEFAULT false,status text DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')),created_at timestamptz DEFAULT now(),deleted_at timestamptz);
CREATE TABLE IF NOT EXISTS products (id text PRIMARY KEY,brand_id text NOT NULL REFERENCES brands(id),name text NOT NULL,description text NOT NULL,category text REFERENCES categories(name),price integer NOT NULL CHECK(price>=0),original_price integer CHECK(original_price>=price),image text,badge text,audience text DEFAULT 'women',rating numeric DEFAULT 0,status text DEFAULT 'draft' CHECK(status IN ('draft','pending','published','rejected')),external_url text,instagram text,video text,tags text[] DEFAULT '{}',created_at timestamptz DEFAULT now(),deleted_at timestamptz);
CREATE TABLE IF NOT EXISTS media (id text PRIMARY KEY,owner_id text NOT NULL REFERENCES users(id),mime text NOT NULL,data bytea NOT NULL,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS product_images (id text PRIMARY KEY,product_id text REFERENCES products(id) ON DELETE CASCADE,url text NOT NULL,position integer NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS product_variants (id text PRIMARY KEY,product_id text REFERENCES products(id) ON DELETE CASCADE,sku text UNIQUE NOT NULL,size text NOT NULL,color text NOT NULL,UNIQUE(product_id,size,color));
CREATE TABLE IF NOT EXISTS inventory (variant_id text PRIMARY KEY REFERENCES product_variants(id),quantity integer NOT NULL DEFAULT 0 CHECK(quantity>=0),updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS brand_followers (user_id text REFERENCES users(id),brand_id text REFERENCES brands(id),created_at timestamptz DEFAULT now(),PRIMARY KEY(user_id,brand_id));
CREATE TABLE IF NOT EXISTS follows (follower_id text REFERENCES users(id),following_id text REFERENCES users(id),PRIMARY KEY(follower_id,following_id),CHECK(follower_id<>following_id));
CREATE TABLE IF NOT EXISTS wishlists (id text PRIMARY KEY,user_id text UNIQUE REFERENCES users(id));
CREATE TABLE IF NOT EXISTS wishlist_items (wishlist_id text REFERENCES wishlists(id),product_id text REFERENCES products(id),created_at timestamptz DEFAULT now(),PRIMARY KEY(wishlist_id,product_id));
CREATE TABLE IF NOT EXISTS carts (id text PRIMARY KEY,user_id text UNIQUE REFERENCES users(id));
CREATE TABLE IF NOT EXISTS cart_items (cart_id text REFERENCES carts(id),variant_id text REFERENCES product_variants(id),quantity integer NOT NULL CHECK(quantity BETWEEN 1 AND 20),PRIMARY KEY(cart_id,variant_id));
CREATE TABLE IF NOT EXISTS orders (id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),total integer NOT NULL CHECK(total>=0),shipping integer NOT NULL DEFAULT 0,address jsonb NOT NULL,status text DEFAULT 'Confirmed' CHECK(status IN ('Pending','Confirmed','Processing','Shipped','Delivered','Cancelled','Refunded')),idempotency_key text NOT NULL,created_at timestamptz DEFAULT now(),UNIQUE(user_id,idempotency_key));
CREATE TABLE IF NOT EXISTS order_items (id text PRIMARY KEY,order_id text REFERENCES orders(id),product_id text REFERENCES products(id),variant_id text REFERENCES product_variants(id),brand_id text REFERENCES brands(id),name text NOT NULL,image text,variant text NOT NULL,price integer NOT NULL,quantity integer NOT NULL CHECK(quantity>0));
CREATE TABLE IF NOT EXISTS payments (id text PRIMARY KEY,order_id text UNIQUE REFERENCES orders(id),provider text NOT NULL,amount integer NOT NULL,status text NOT NULL CHECK(status IN ('Pending','Processing','Successful','Failed','Refunded')),reference text,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS reviews (id text PRIMARY KEY,user_id text REFERENCES users(id),product_id text REFERENCES products(id),rating integer CHECK(rating BETWEEN 1 AND 5),body text,created_at timestamptz DEFAULT now(),UNIQUE(user_id,product_id));
CREATE TABLE IF NOT EXISTS reels (id text PRIMARY KEY,brand_id text REFERENCES brands(id),product_id text REFERENCES products(id),caption text,image text,video text,creator text,likes integer DEFAULT 0,views integer DEFAULT 0,status text DEFAULT 'published' CHECK(status IN ('draft','pending','published','rejected')),created_at timestamptz DEFAULT now(),deleted_at timestamptz);
CREATE TABLE IF NOT EXISTS reel_likes (user_id text REFERENCES users(id),reel_id text REFERENCES reels(id),PRIMARY KEY(user_id,reel_id));
CREATE TABLE IF NOT EXISTS reel_saves (user_id text REFERENCES users(id),reel_id text REFERENCES reels(id),PRIMARY KEY(user_id,reel_id));
CREATE TABLE IF NOT EXISTS reel_comments (id text PRIMARY KEY,user_id text REFERENCES users(id),reel_id text REFERENCES reels(id),body text NOT NULL,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS reel_shares (id text PRIMARY KEY,user_id text REFERENCES users(id),reel_id text REFERENCES reels(id),created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS reel_viewers (user_id text REFERENCES users(id),reel_id text REFERENCES reels(id),created_at timestamptz DEFAULT now(),PRIMARY KEY(user_id,reel_id));
CREATE TABLE IF NOT EXISTS posts (id text PRIMARY KEY,brand_id text REFERENCES brands(id),body text NOT NULL,image text,status text DEFAULT 'draft',created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS premium_plans (id text PRIMARY KEY,name text NOT NULL,price integer CHECK(price>=0),product_limit integer NOT NULL,reel_limit integer NOT NULL,features jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS subscriptions (user_id text PRIMARY KEY REFERENCES users(id),plan_id text REFERENCES premium_plans(id),status text DEFAULT 'active',created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS advertisements (id text PRIMARY KEY,title text NOT NULL,description text,image text,video text,brand_id text REFERENCES brands(id),target_url text NOT NULL,placement text NOT NULL,status text DEFAULT 'Draft' CHECK(status IN ('Draft','Active','Expired','Disabled')),start_date timestamptz,end_date timestamptz,CHECK(end_date IS NULL OR end_date>start_date));
CREATE TABLE IF NOT EXISTS notifications (id text PRIMARY KEY,user_id text REFERENCES users(id),message text NOT NULL,read boolean DEFAULT false,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS admin_users (user_id text PRIMARY KEY REFERENCES users(id));
CREATE TABLE IF NOT EXISTS reports (id text PRIMARY KEY,user_id text REFERENCES users(id),reel_id text REFERENCES reels(id),reason text NOT NULL,status text DEFAULT 'open',created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS settings (key text PRIMARY KEY,value jsonb NOT NULL);
CREATE INDEX IF NOT EXISTS products_brand_idx ON products(brand_id);
CREATE INDEX IF NOT EXISTS products_discovery_idx ON products(status,audience,category) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS reels_feed_idx ON reels(status,created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS orders_user_idx ON orders(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS notifications_user_idx ON notifications(user_id,read);
CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS comments_reel_idx ON reel_comments(reel_id,created_at);
